name: Update Seismogram

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [update_seismos]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install matplotlib requests obspy

      - name: Run script
        run: python seismos.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add seismo_live.png
          git commit -m "Update seismogram" || exit 0
          git push
